# Project configuration
general:
  projectName: 'RiskManagement'
  productiveBranch: 'main'

# Stage configuration
stages:
  productionDeployment:
    cfTargets:
    - org: '33562e87trial'
      space: 'dev'
      appName: 'RiskManagement'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      credentialsId: 'cfdeploy'